### ISSUE TITLE
Failed video file

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1005]
Joey tried to upload a large (12.4GB) video file on Wednesday, which failed. It's a PAL video, but he was able to upload a much smaller version of the file, so PAL shouldn't be the problem. Since the error is a "Net::ReadTimeout" error, I imagine it's the size of the file that's failing:

```
Error Net::ReadTimeout
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http.rb:1382:in `request'
/home/drs/cerberus/shared/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/home/drs/cerberus/releases/20160803031211/app/jobs/content_creation_job.rb:154:in `block in large_upload'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http.rb:852:in `start'
/home/drs/.rvm/rubies/ruby-2.0.0-p647/lib/ruby/2.0.0/net/http.rb:582:in `start'
/home/drs/cerberus/releases/20160803031211/app/jobs/content_creation_job.rb:153:in `large_upload'
/home/drs/cerberus/releases/20160803031211/app/jobs/content_creation_job.rb:76:in `run'
/home/drs/cerberus/releases/20160803031211/lib/cerberus/resque/queue.rb:24:in `perform'
```

He and I both tried to upload the file using a wired connection on campus with the same result. Is it the size that's preventing the file from succeeding, or is it something else? Let me know if you want to see the file.

**Comment by dgcliff** [comment]
Fixed (at least for now) with aecd67a7b5fe77b559243ac78fc6d45780b27bce
